<a href="https://colab.research.google.com/github/repovitamD/udemy--lessen/blob/main/241116.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

データの読み込み

In [1]:
import numpy as np

In [3]:
from sklearn import datasets

In [4]:
iris = datasets.load_iris()

In [6]:
print(iris.data[:10])
print(iris.target[:10])
print(iris.data.shape)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
[0 0 0 0 0 0 0 0 0 0]
(150, 4)


データの前処理

In [7]:
from sklearn import preprocessing

In [9]:
from keras.utils import to_categorical

In [14]:
#データの標準化を実施。
#まずはメソッドを読み込んで、
scaler = preprocessing.StandardScaler()
#メソッドにirisデータセットを処理させる。
scaler.fit(iris.data)

x=scaler.transform(iris.data)
print(x[:10])

t=to_categorical(iris.target)
print(t[:10])
#正解ラベルは0,1,2だが、ワンホット表現に変換されるので0ならば100、1ならば010、2ならば001となる。

[[-0.90068117  1.01900435 -1.34022653 -1.3154443 ]
 [-1.14301691 -0.13197948 -1.34022653 -1.3154443 ]
 [-1.38535265  0.32841405 -1.39706395 -1.3154443 ]
 [-1.50652052  0.09821729 -1.2833891  -1.3154443 ]
 [-1.02184904  1.24920112 -1.34022653 -1.3154443 ]
 [-0.53717756  1.93979142 -1.16971425 -1.05217993]
 [-1.50652052  0.78880759 -1.34022653 -1.18381211]
 [-1.02184904  0.78880759 -1.2833891  -1.3154443 ]
 [-1.74885626 -0.36217625 -1.34022653 -1.3154443 ]
 [-1.14301691  0.09821729 -1.2833891  -1.44707648]]
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


訓練データとテストデータに分割する。

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
x_train, x_test, t_train, t_test = train_test_split(x,t,train_size=0.75)

In [17]:
print(x_train.shape)

(112, 4)


モデルの構築

In [20]:
from keras.models import Sequential
#Sequentialモデルは、層を順に積み重ねることでモデルを構築するための方法で、シンプルなネットワーク構造に適しています。
#一方、Functional APIを使用したモデル構築方法は、より複雑なモデルアーキテクチャに対応可能で、多入力、多出力、共有層を持つモデルの構築が可能です。

In [22]:
from keras.layers import Dense, Activation
#Denseレイヤーは、全結合層(全結合ニューラルネットワーク)の基本的な構成要素であり、
#各入力ニューロンが次のレイヤーのすべてのニューロンに接続されている、いわゆる全結合層（Fully Connected Layer）です。

#全結合層（fully connected layer）はニューラルネットワークの層の一種で、各ニューロンが前の層のすべてのニューロンと接続されている層を指します。


In [ ]:
model=Sequential()
model.add(Dense(32, input_dim=4))
#32のノードを持つ全結合層を追加した。また、入力数が4つであると指定した。irisデータが4つの数値が一つの花を示すためである。